In [1]:
from sklearn.datasets import load_iris

In [2]:
#load the data and store it in the variable(iris)
iris=load_iris()
#special type in sklearn known as Bunch
type(iris)

sklearn.utils.Bunch

In [3]:
#print the dataset in the iris
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [18]:
#name of the four features
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [19]:
#target value for the dataset,representation of each observation
print (iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#species name fromm the dataset
print(iris.target_names)

In [20]:
#feature and response must be NumPy arrays
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
#the feature and response must have a shape
#first dimension = no of records , second dimensions = no of features
iris.data.shape

(150, 4)

In [22]:
iris.target.shape

(150,)

In [23]:
#store feature matrix in "X"
X=iris.data
#store response matrix in "y"
y=iris.target

# Scikit-Learn 4-step modelling pattern

# Step1: import the class and plan to use

In [24]:
from sklearn.neighbors import KNeighborsClassifier

# Step2: "Instantiate" the "estimator"

1 "Estimator" is scikit term for model

2 "Instantiate"  means making the instance of

In [25]:
knn=KNeighborsClassifier(n_neighbors=1)

3  Name doesn't matter

4  Can specify tuning parameters (aka="hyperparameters") during this step

5  All parameters are not specified set to thier defaults 

In [26]:
print (knn)

KNeighborsClassifier(n_neighbors=1)


# Step3: Fit the Model("Model Training")

Model is learning the relationship between the X and y ,occurs in place

In [27]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

# Step4: Predict the response for a new observation

New observations are out of sample

Uses the information learned during the training process

In [28]:
solution1=knn.predict([[3 ,5 ,5 ,2]])
solution1.shape

(1,)

Returns a Array

Can predict multiple values

In [29]:
x_new=[[3,2,4,3],[4,5,4,3]]
solution2=knn.predict(x_new)
solution2

array([2, 1])

# Using a different value for K

In [30]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
knn.predict(x_new)

array([1, 1])

# Using a Different classification model(L.R)

In [31]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X,y)
val=logreg.predict([[3,5,4,3]])
iris.target_names[val]

/home/bhuvi/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array(['virginica'], dtype='<U10')